spring.application.name: heroes-admin-app

spring:
  datasource.url: jdbc:mysql://localhost:3306/heroes

  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    spring.jpa.properties.hibernate.format_sql: true
    open-in-view: false
    properties.hibernate.enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.MySQL8Dialect  

  jackson.mapper.accept-case-insensitive-enums: true

